language: go

git:
  depth: 1

notifications:
  email: false

services:
  - docker

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.17.1
script:
  - ./bin/golangci-lint run
  - go test ./src -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  on:
    tags: true
  provider: script
  script: bash ci/deploy_images.sh
